version: '2'
services:
    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
    es:
        image: elasticsearch
        ports:
            - "9200:9200"
    springboot:
        image: eventbook/springbootpoc:1.5
        ports:
            - "8080:8080"
        links:
            - rabbitmq
            - mysql
            - es